"use client";
import {useMemo,useState} from "react";
import {LayoutDashboard,Car,ClipboardCheck,Inbox,Menu,Search,Bell,Plus,MoreHorizontal,Clock,User,Calendar,Share2,Sparkles,Send,Check,Container,Truck,FileWarning} from "lucide-react";
type Page="dashboard"|"cars"|"tracking"|"line"; type Status="Booked"|"Available"|"Exported"|"P.Office"|"Repair"|"Pending";
const data=[["24206","TRAVO 2.8 4WD AT","WAN","Booked",758000,"MR0KA8CD1P1254206"],["7ขผ-4366","RAPTOR 2.0 Bi-Turbo","AOR","Available",1120000,"MPBUMFE60PXJ84366"],["ผข-1603","REVO 2.4 ENTRY MT","GWANG","Repair",468000,"MR0JB8DD4M0161603"],["ญญ-2633","VIGO CHAMP 3.0 G AT","STOCK","Exported",395000,"MR0FZ29G301122633"],["3ฒฬ-8912","REVO PRERUNNER 2.4 AT","BE FORWARD","P.Office",619000,"MR0HA3CD8N1188912"],["บห-7741","TRAVO 2.8 HIGH 4WD","WAN","Pending",845000,"MR0KB8CD0P1077741"]] as [string,string,string,Status,number,string][];
const nav=[["dashboard","Dashboard",LayoutDashboard],["cars","Cars inventory",Car],["tracking","Order tracking",ClipboardCheck],["line","LINE inbox",Inbox]] as const;
const tasks=[["ผข-1603","ตรวจช่วงล่างและถ่ายรูปหลังซ่อม","ช่าง","Tum","วันนี้ 16:00","กำลังทำ"],["24206","เตรียมเอกสารส่งออกและสำเนาเล่ม","ทีมขาย","Wan","วันนี้ 17:30","รอตรวจ"],["7ขผ-4366","ถ่ายรูป 30 มุม + วิดีโอเครื่องยนต์","คลัง","Ake","พรุ่งนี้ 10:00","งานใหม่"],["บห-7741","ยืนยันยอดคงเหลือกับลูกค้า","ทีมขาย","Gwang","พรุ่งนี้ 12:00","รอลูกค้า"]];
const color:Record<Status,string>={Booked:"blue",Available:"green",Exported:"gray","P.Office":"purple",Repair:"amber",Pending:"orange"};
export default function Home(){const[page,setPage]=useState<Page>("dashboard"),[open,setOpen]=useState(false);return <div className="shell"><aside className={open?"open":""}><div className="brand"><b>V4</b><span><strong>VIGO4U</strong><small>EXPORT OPS</small></span></div><nav>{nav.map(([id,l,I])=><button className={page===id?"active":""} onClick={()=>{setPage(id);setOpen(false)}} key={id}><I size={19}/>{l}{id==="line"&&<i>4</i>}</button>)}</nav><div className="capacity"><small>YARD CAPACITY</small><b>87 / 120 cars</b><div><i/></div><small>33 spaces available</small></div><div className="user"><b>ES</b><span>Es VIGO4U<small>Operations manager</small></span></div></aside><main><header><button className="hamb" onClick={()=>setOpen(true)}><Menu/></button><div><h1>{nav.find(x=>x[0]===page)?.[1]}</h1><p>Wednesday, 2 September 2026 · Bangkok Yard</p></div><span className="head"><button><Search/></button><button><Bell/></button><b>ES</b></span></header><section>{page==="dashboard"&&<Dashboard setPage={setPage}/>} {page==="cars"&&<Cars/>} {page==="tracking"&&<Tracking/>} {page==="line"&&<Line/>}</section><footer>{nav.map(([id,l,I])=><button className={page===id?"active":""} onClick={()=>setPage(id)} key={id}><I/><small>{l.split(" ")[0]}</small></button>)}</footer></main>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}</div>}
function Title({title,sub,button}:{title:string,sub:string,button?:string}){return <div className="title"><div><h2>{title}</h2><p>{sub}</p></div>{button&&<button className="primary"><Plus/> {button}</button>}</div>}
function Dashboard({setPage}:{setPage:(p:Page)=>void}){const k=[["รถทั้งหมด","87","มูลค่า ฿52.4M",Car],["จองแล้วยังไม่ส่ง","18","3 คันเกินกำหนด",Clock],["ส่งออกแล้ว","42","เดือนนี้ +12",Container],["พร้อมขาย","27","31% ของสต๊อก",Check],["รถรับพรุ่งนี้","6","เช็กตารางรับรถ",Truck],["Not on vigoasia","9","ต้องลงเว็บไซต์",FileWarning],["Not on beforward","14","ต้องลงเว็บไซต์",FileWarning]] as const;return <><Title title="ภาพรวมวันนี้" sub="อัปเดตล่าสุด 15:42 น." button="เพิ่มรถ"/><div className="kpis">{k.map(([l,v,n,I])=><article key={l}><I/><span>{l}</span><b>{v}</b><small>{n}</small></article>)}</div><div className="charts"><article className="panel"><Head t="Buyer breakdown" s="รถจองและส่งออกเดือนนี้"/><div className="donutrow"><div className="donut"><b>60<small>cars</small></b></div><div className="legend">{[["BE FORWARD",22],["Africa buyers",17],["Pacific",12],["Other",9]].map(x=><p key={x[0]}><i/>{x[0]}<b>{x[1]}</b></p>)}</div></div></article><article className="panel"><Head t="รถแยกตาม Agent" s="จำนวนรถที่รับผิดชอบ"/><div className="bars">{[["WAN",24],["AOR",19],["GWANG",17],["STOCK",15],["BE FORWARD",12]].map(x=><p key={x[0]}><span>{x[0]}</span><i><b style={{width:Number(x[1])*4+"%"}}/></i><strong>{x[1]}</strong></p>)}</div></article></div><article className="panel tablepanel"><Head t="รถอัปเดตล่าสุด" s="รายการเปลี่ยนแปลงล่าสุด" action={()=>setPage("cars")}/><Table rows={data.slice(0,5)}/></article></>}
function Head({t,s,action}:{t:string,s:string,action?:()=>void}){return <div className="panelhead"><div><h3>{t}</h3><p>{s}</p></div>{action&&<button onClick={action}>ดูทั้งหมด →</button>}</div>}
function Table({rows}:{rows:typeof data}){return <div className="scroll"><table><thead><tr><th>PLATE</th><th>SPEC / CHASSIS</th><th>SALE SUPPORT</th><th>STATUS</th><th>PRICE</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td><strong>{r[0]}</strong><small>updated recently</small></td><td><b>{r[1]}</b><small>{r[5]}</small></td><td><i className="agent">{r[2].slice(0,2)}</i>{r[2]}</td><td><span className={"status "+color[r[3]]}>{r[3]}</span></td><td><b>฿{r[4].toLocaleString()}</b></td><td><MoreHorizontal/></td></tr>)}</tbody></table></div>}
function Cars(){const[q,setQ]=useState(""),[f,setF]=useState("All");const rows=useMemo(()=>data.filter(r=>(f==="All"||r[3]===f)&&r.join(" ").toLowerCase().includes(q.toLowerCase())),[q,f]);return <><Title title="Cars inventory" sub={rows.length+" vehicles shown · Total stock value ฿52,438,000"} button="Add vehicle"/><div className="toolbar panel"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search plate, chassis or spec..."/></label><div>{["All","Booked","Available","Exported"].map(x=><button className={f===x?"active":""} onClick={()=>setF(x)} key={x}>{x}</button>)}</div></div><article className="panel tablepanel"><Table rows={rows}/></article></>}
function Tracking(){const[t,setT]=useState("ทั้งหมด");return <><Title title="งานติดตามรถ" sub="4 งานค้าง · 2 งานครบกำหนดวันนี้" button="เพิ่มงาน"/><div className="chips">{["ทั้งหมด","ทีมขาย","คลัง","ช่าง"].map(x=><button className={t===x?"active":""} onClick={()=>setT(x)} key={x}>{x}</button>)}</div><div className="tasks">{tasks.filter(x=>t==="ทั้งหมด"||x[2]===t).map(x=><article key={x[0]}><div><b>🚙 {x[0]}</b><span>{x[5]}</span></div><h3>{x[1]}</h3><p><User/> {x[3]} <Calendar/> {x[4]}</p><footer><small>{x[2]}</small><button>เปิดงาน →</button></footer></article>)}</div><div className="taskactions"><button><Inbox/> รับงานจาก LINE</button><button><Share2/> แชร์</button></div></>}
function Line(){const[text,setText]=useState("รถ 24206 ลูกค้ายืนยันแล้ว ให้ WAN เตรียมเอกสาร export ภายในวันนี้ 5 โมง\nผข-1603 ช่วงล่างมีเสียง ให้ตั้มเช็กและถ่ายรูปส่งด้วย"),[show,setShow]=useState(true),[done,setDone]=useState(false);return <><Title title="LINE Inbox Review" sub="วางข้อความจาก LINE แล้วตรวจงานก่อนบันทึก"/><div className="linegrid"><article className="panel compose"><Head t="ข้อความจาก LINE" s="รองรับหลายข้อความในครั้งเดียว"/><textarea value={text} onChange={e=>{setText(e.target.value);setShow(false)}}/><div><small>{text.length} characters</small><button className="primary" onClick={()=>setShow(true)}><Sparkles/> Analyze</button></div></article><article className="panel preview"><Head t="AI task preview" s={show?"พบ 2 งานจากข้อความนี้":"กด Analyze เพื่อแยกรายการงาน"}/>{show&&<div className="ailist">{[["24206","เตรียมเอกสาร Export","WAN","วันนี้ 17:00"],["ผข-1603","ตรวจช่วงล่างและถ่ายรูป","Tum","วันนี้"]].map(x=><label key={x[0]}><input type="checkbox" defaultChecked/><div><b>{x[1]}</b><strong>{x[0]}</strong><p><User/> {x[2]} <Clock/> {x[3]}</p></div></label>)}<button className="confirm" onClick={()=>setDone(true)}>{done?<><Check/> บันทึกงานแล้ว</>:<><Send/> Confirm selected (2)</>}</button></div>}</article></div></>}
